import { useCallback, useEffect, useRef, useState } from 'react';
import { Text, View } from 'react-native';
import * as Location from 'expo-location';
import MapView, { Marker, type Region } from 'react-native-maps';
import { Action, Card, styles } from '../../components/ui';
import { fetchNearby, publishPresence, stopPresence, type NearbyUser } from './api';
import { loadDemoUser, type DemoUser } from './identity';
import { shouldPublishLocation, type Coordinates } from './throttle';
import { locationAvailability } from './status';

type MapStatus = 'loading' | 'ready' | 'permission-denied' | 'location-disabled' | 'offline' | 'empty';
export function MapScreen() {
  const [status, setStatus] = useState<MapStatus>('loading'); const [sharing, setSharing] = useState(true);
  const [user, setUser] = useState<DemoUser | null>(null); const [current, setCurrent] = useState<Location.LocationObject | null>(null); const [nearby, setNearby] = useState<NearbyUser[]>([]);
  const watcher = useRef<Location.LocationSubscription | null>(null); const poller = useRef<ReturnType<typeof setInterval> | null>(null); const lastSent = useRef<{ coordinates: Coordinates; sentAt: number } | null>(null); const mounted = useRef(true);
  const currentRef = useRef<Location.LocationObject | null>(null);
  const coordinatesOf = (location: Location.LocationObject): Coordinates => ({ latitude: location.coords.latitude, longitude: location.coords.longitude });
  const refreshNearby = useCallback(async (demoUser: DemoUser, location: Location.LocationObject) => { try { const users = await fetchNearby(demoUser.userId, coordinatesOf(location)); if (mounted.current) { setNearby(users); setStatus(users.length ? 'ready' : 'empty'); } } catch { if (mounted.current) setStatus('offline'); } }, []);
  const publish = useCallback(async (demoUser: DemoUser, location: Location.LocationObject, force = false) => { const coordinates = coordinatesOf(location); const now = Date.now(); if (!force && !shouldPublishLocation(lastSent.current, coordinates, now)) return; try { await publishPresence({ ...coordinates, userId: demoUser.userId, displayName: demoUser.displayName, accuracyMeters: location.coords.accuracy ?? 100, capturedAt: new Date().toISOString() }); lastSent.current = { coordinates, sentAt: now }; if (mounted.current) setStatus('ready'); } catch { if (mounted.current) setStatus('offline'); } }, []);
  const stopSharing = useCallback(async () => { setSharing(false); watcher.current?.remove(); watcher.current = null; if (poller.current) { clearInterval(poller.current); poller.current = null; } if (user) { try { await stopPresence(user.userId); } catch { /* stopped locally even if API is unavailable */ } } }, [user]);
  const startSharing = useCallback(async (demoUser: DemoUser) => { setSharing(true); try { const permission = await Location.getForegroundPermissionsAsync(); const availability = locationAvailability(permission.status === Location.PermissionStatus.GRANTED, await Location.hasServicesEnabledAsync()); if (availability !== 'ready') { setStatus(availability); return; } watcher.current = await Location.watchPositionAsync({ accuracy: Location.Accuracy.Balanced, timeInterval: 12_000, distanceInterval: 25 }, (location) => { currentRef.current = location; setCurrent(location); void publish(demoUser, location); void refreshNearby(demoUser, location); }); } catch { setStatus('offline'); } }, [publish, refreshNearby]);
  useEffect(() => { mounted.current = true; let cancelled = false; let demoUserForCleanup: DemoUser | null = null; void (async () => { const demoUser = await loadDemoUser(); demoUserForCleanup = demoUser; if (cancelled) return; setUser(demoUser); const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== Location.PermissionStatus.GRANTED) { setStatus('permission-denied'); return; } if (!(await Location.hasServicesEnabledAsync())) { setStatus('location-disabled'); return; } try { const location = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); if (cancelled) return; currentRef.current = location; setCurrent(location); await publish(demoUser, location, true); await refreshNearby(demoUser, location); await startSharing(demoUser); poller.current = setInterval(() => { if (currentRef.current) void refreshNearby(demoUser, currentRef.current); }, 15_000); } catch { if (mounted.current) setStatus('offline'); } })(); return () => { cancelled = true; mounted.current = false; watcher.current?.remove(); watcher.current = null; if (poller.current) clearInterval(poller.current); if (demoUserForCleanup) void stopPresence(demoUserForCleanup.userId).catch(() => undefined); }; }, [publish, refreshNearby, startSharing]);
  const region: Region | undefined = current ? { latitude: current.coords.latitude, longitude: current.coords.longitude, latitudeDelta: 0.004, longitudeDelta: 0.004 } : undefined;
  return <View style={{ gap: 16 }}><Text style={styles.eyebrow}>NEARBY / DEMO PRESENCE</Text><Text style={styles.title}>Find your space.</Text><Text style={styles.body}>Nearby positions are approximate and expire after one minute. Demo identity: {user?.displayName ?? 'loading…'}.</Text>{status === 'loading' && <Card><Text style={styles.body}>Loading your location…</Text></Card>}{status === 'permission-denied' && <Card><Text style={styles.body}>Location permission is denied. Enable it in Settings to share your position.</Text></Card>}{status === 'location-disabled' && <Card><Text style={styles.body}>Location services are disabled on this device.</Text></Card>}{status === 'offline' && <Card><Text style={styles.body}>Presence service is unavailable. Your location is not being shared until it reconnects.</Text></Card>}{region && <MapView style={{ height: 360, borderRadius: 20 }} initialRegion={region} region={region} showsUserLocation>{nearby.map((person) => <Marker key={person.userId} coordinate={person.position} title={person.displayName} description={`${person.distanceMeters} m away`} />)}</MapView>}{status === 'empty' && <Text style={styles.body}>No active nearby users.</Text>}{nearby.length > 0 && <Text style={styles.body}>{nearby.length} nearby user{nearby.length === 1 ? '' : 's'} · closest {nearby[0]?.distanceMeters} m</Text>}{sharing ? <Action title="Stop sharing location" onPress={() => { void stopSharing(); }} /> : user && <Action title="Start sharing location" onPress={() => { void startSharing(user); }} />}</View>;
}
