import { useCallback, useEffect, useMemo, useState } from 'react';
import { Text, View } from 'react-native';
import { Action, Card, styles } from '../../components/ui';
import { acceptChallenge, acceptChallengeConfig, createChallenge, declineChallenge, listChallenges, startChallenge, updateChallengeConfig, type Challenge, type ChallengeConfig } from './api';
import { loadDemoUser, type DemoUser } from '../location/identity';
import type { NearbyUser } from '../location/api';
import { isValidWorkoutSession, type WorkoutSessionConfig } from '../workout/session';

interface ChallengeScreenProps { opponent: NearbyUser | null; onBack: () => void; onStartWorkout: (session: WorkoutSessionConfig) => void; }
const editable = (config: ChallengeConfig) => ({ exercise: config.exercise, setCount: config.setCount, targetReps: config.targetReps, restSeconds: config.restSeconds, matchTimeLimitSeconds: config.matchTimeLimitSeconds });
export function ChallengeScreen({ opponent, onBack, onStartWorkout }: ChallengeScreenProps) {
  const [user, setUser] = useState<DemoUser | null>(null); const [challenges, setChallenges] = useState<Challenge[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async (demoUser: DemoUser) => { try { setChallenges(await listChallenges(demoUser.userId)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load challenges.'); } finally { setLoading(false); } }, []);
  useEffect(() => { let mounted = true; void loadDemoUser().then((demoUser) => { if (!mounted) return; setUser(demoUser); void refresh(demoUser); }).catch(() => { if (mounted) { setError('Could not load demo identity.'); setLoading(false); } }); return () => { mounted = false; }; }, [refresh]);
  useEffect(() => { if (!user) return; const timer = setInterval(() => { void refresh(user); }, 5000); return () => clearInterval(timer); }, [refresh, user]);
  const activeChallenge = useMemo(() => challenges.find((item) => ['accepted', 'configuring', 'ready', 'active'].includes(item.status) && (item.senderId === user?.userId || item.receiverId === user?.userId)), [challenges, user]);
  useEffect(() => { if (activeChallenge?.status !== 'active') return; const session: unknown = { mode: 'challenge', ...activeChallenge.configuration, challengeId: activeChallenge.challengeId, startedAt: activeChallenge.startedAt }; if (isValidWorkoutSession(session)) onStartWorkout(session); else setError('The shared workout configuration or start time is invalid; camera session not started.'); }, [activeChallenge, onStartWorkout]);
  const mutate = async (operation: () => Promise<Challenge>) => { setBusy(true); setError(null); try { const updated = await operation(); setChallenges((current) => current.some((item) => item.challengeId === updated.challengeId) ? current.map((item) => item.challengeId === updated.challengeId ? updated : item) : [updated, ...current]); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Challenge request failed.'); } finally { setBusy(false); } };
  const respond = (challenge: Challenge, action: 'accept' | 'decline') => { if (user) void mutate(() => action === 'accept' ? acceptChallenge(user.userId, challenge.challengeId) : declineChallenge(user.userId, challenge.challengeId)); };
  const config = activeChallenge?.configuration;
  const changeConfig = (field: 'setCount' | 'targetReps' | 'restSeconds' | 'matchTimeLimitSeconds', delta: number) => { if (!user || !activeChallenge || !config || activeChallenge.locked) return; const bounds = { setCount: [1, 3], targetReps: [1, 50], restSeconds: [0, 300], matchTimeLimitSeconds: [30, 1800] }[field]; const min = bounds[0] ?? 0; const max = bounds[1] ?? 0; const value = Math.max(min, Math.min(max, config[field] + delta)); void mutate(() => updateChallengeConfig(user.userId, activeChallenge.challengeId, { ...editable(config), [field]: value })); };
  return <View style={{ gap: 16 }}>
    <Action title="Back to map" onPress={onBack} /><Text style={styles.eyebrow}>PROXIMITY / CHALLENGES</Text><Text style={styles.title}>Choose your next test.</Text>
    <Text style={styles.body}>Demo identity: {user?.displayName ?? 'loading…'} (local-only, not authentication).</Text>
    {error && <Card><Text style={styles.body}>Challenge error: {error}</Text><Action title="Retry" onPress={() => { if (user) void refresh(user); }} /></Card>}
    {opponent && <Card><Text style={styles.heading}>Selected opponent</Text><Text style={styles.body}>{opponent.displayName} · approximately {opponent.distanceMeters} m away</Text><Action title={busy ? 'Sending…' : 'Send challenge'} onPress={() => { if (user) void mutate(() => createChallenge(user, opponent)); }} /></Card>}
    {loading ? <Text style={styles.body}>Loading challenges…</Text> : challenges.filter((challenge) => challenge.receiverId === user?.userId && challenge.status === 'pending').map((challenge) => <Card key={challenge.challengeId}><Text style={styles.heading}>Incoming challenge</Text><Text style={styles.body}>{challenge.senderDisplayName} · {challenge.proximityMeters} m away</Text><View style={{ flexDirection: 'row', gap: 8 }}><Action title="Accept" onPress={() => respond(challenge, 'accept')} /><Action title="Decline" onPress={() => respond(challenge, 'decline')} /></View></Card>)}
    {challenges.filter((challenge) => challenge.senderId === user?.userId).map((challenge) => <Text key={challenge.challengeId} style={styles.body}>Outgoing: {challenge.receiverDisplayName} · {challenge.status}</Text>)}
    {activeChallenge && config && <Card><Text style={styles.heading}>Shared squat configuration</Text><Text style={styles.body}>Exercise: bodyweight squat · Version {config.configVersion}</Text><Text style={styles.body}>Sender: {activeChallenge.acceptance.senderAcceptedAt ? 'accepted' : 'waiting'} · Receiver: {activeChallenge.acceptance.receiverAcceptedAt ? 'accepted' : 'waiting'}</Text>{(['setCount', 'targetReps', 'restSeconds', 'matchTimeLimitSeconds'] as const).map((field) => <View key={field} style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Text style={styles.body}>{field === 'setCount' ? 'Sets' : field === 'targetReps' ? 'Target reps' : field === 'restSeconds' ? 'Rest seconds' : 'Match time seconds'}: {config[field]}</Text><View style={{ flexDirection: 'row', gap: 8 }}><Action title="−" onPress={() => changeConfig(field, -1)} /><Action title="+" onPress={() => changeConfig(field, 1)} /></View></View>)}<Text style={styles.body}>{activeChallenge.locked ? 'Workout settings locked' : activeChallenge.status === 'ready' ? 'Both players ready' : 'Waiting for the other player'}</Text>{activeChallenge.status === 'configuring' && !activeChallenge.acceptance.senderAcceptedAt && !activeChallenge.acceptance.receiverAcceptedAt && <Text style={styles.body}>Configuration changed; acceptance reset.</Text>}{(activeChallenge.status === 'accepted' || activeChallenge.status === 'configuring') && <Action title="Accept configuration" onPress={() => user && void mutate(() => acceptChallengeConfig(user.userId, activeChallenge.challengeId))} />}{activeChallenge.status === 'ready' && <Action title="Start workout" onPress={() => user && void mutate(() => startChallenge(user.userId, activeChallenge.challengeId))} />}{activeChallenge.status === 'active' && <Text style={styles.body}>Workout locked. Rep tracking is the next step.</Text>}</Card>}
  </View>;
}
